In [17]:
# learning material: http://www.adeveloperdiary.com/data-science/machine-learning/forward-and-backward-algorithm-in-hidden-markov-model/
# i modified the code slightly so it can handle end state
import numpy as np

# transition probability
a = np.array(((0.367, 0.333),(0.333, 0.3)))

# emission probability
b = np.array(((0.3, 0.7), (0.35, 0.65)))

# probability from start state to M and F
init_transition_prob = np.array((0.7, 0.3))

# probability from M and F to end state
final_transition_prob = np.array((0.3, 0.367))

# observation (0 is sad, 1 is happy)
V = np.array((0,0,1))

In [3]:
a

array([[0.367, 0.333],
       [0.333, 0.3  ]])

In [4]:
b

array([[0.3 , 0.7 ],
       [0.35, 0.65]])

In [14]:
init_transition_prob

array([0.7, 0.3])

In [18]:
final_transition_prob

array([0.3  , 0.367])

In [29]:
def forward(V, a, b, init_transition_prob, final_transition_prob):
    alpha = np.zeros((V.shape[0], a.shape[0]))
    alpha[0, :] = init_transition_prob * b[:, V[0]]
 
    for t in range(1, V.shape[0]):
        for j in range(a.shape[0]):
            # Matrix Computation Steps
            #                  ((1x2) . (1x2))      *     (1)
            #                        (1)            *     (1)
            alpha[t, j] = alpha[t - 1].dot(a[:, j]) * b[j, V[t]]
 
    return alpha, np.sum(alpha[-1] * final_transition_prob)
 
alpha, P = forward(V, a, b, init_transition_prob, final_transition_prob)
print("alpha (left is Mother, right is Father, row is alpha 1 to alpha 3 respectively)\n", alpha)
print(P)

alpha (left is Mother, right is Father, row is alpha 1 to alpha 3 respectively)
 [[0.21       0.105     ]
 [0.0336105  0.0355005 ]
 [0.0169097  0.01419759]]
0.010283426812574999


In [28]:
def backward(V, a, b, init_transition_prob, final_transition_prob):
    beta = np.zeros((V.shape[0], a.shape[0]))
 
    # setting beta(T) = 1
    beta[V.shape[0] - 1] = final_transition_prob
 
    # Loop in backward way from T-1 to
    # Due to python indexing the actual loop will be T-2 to 0
    for t in range(V.shape[0] - 2, -1, -1):
        for j in range(a.shape[0]):
            beta[t, j] = (beta[t + 1] * b[:, V[t + 1]]).dot(a[j, :])
    
    return beta, np.sum(beta[0] * init_transition_prob * b.T[V[0]])
 
beta, P = backward(V, a, b, init_transition_prob, final_transition_prob)
print("beta (left is Mother, right is Father, row is beta 3 to beta 1 respectively)\n", beta)
print(P)

beta (left is Mother, right is Father, row is beta 3 to beta 1 respectively)
 [[0.03372268 0.03049204]
 [0.15650715 0.141495  ]
 [0.3        0.367     ]]
0.010283426812574999
